backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/img/uploads'
public_folder: /img/uploads

collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    files:
      - label: 'Project Gallery'
        name: 'project_gallery'
        file: 'content/project_gallery.md'
        fields:
          - { label: Title, name: projects_title, widget: string }
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Caption, name: caption, widget: text },
                ],
            }
