backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'static/uploads'

collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    files:
      - label: 'Projects Gallery'
        name: 'projectsGallery'
        file: 'content/projects.md'
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Caption, name: caption, widget: text },
                ],
            }
